version: '2'
services:
  database:
    image: mariadb
    volumes:
      - "./srv/database:/var/lib/mysql"
    environment:
      ## Database settings
      ## change if you want it to be more secure.
      - "MYSQL_ROOT_PASSWORD=apassword"
      - "MYSQL_DATABASE=pterodb"
      - "MYSQL_USER=ptero"
      - "MYSQL_PASSWORD=pterodbpass"

  cache:
    image: redis:alpine

  panel:
    build: .
    links:
      - database
      - cache
    volumes:
      - "./srv/var/:/app/var/"
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:panel.occultus.network"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
    environment:
      ## These are defaults and should be left alone
      - "APP_ENV=production"
      - "APP_DEBUG=false"
      - "APP_THEME=pterodactyl"
      - "APP_CLEAR_TASKLOG=720"
      - "APP_DELETE_MINUTES=10"
      - "APP_ENVIRONMENT_ONLY=false"
      - "QUEUE_HIGH=high"
      - "QUEUE_STANDARD=standard"
      - "QUEUE_LOW=low"
      ## Cache settings
      - "CACHE_DRIVER=redis"
      - "SESSION_DRIVER=redis"
      - "QUEUE_DRIVER=redis"
      - "REDIS_HOST=cache"
      - "REDIS_PASSWORD=null"
      - "REDIS_PORT=6379"
      ## Domain settings
      - "APP_URL=https://panel.occultus.network"
      - "TRUSTED_PROXIES=*"
      ## Timezone settings
      - "APP_TIMEZONE=America/New_York"
      ## Service egg settings
      - "APP_SERVICE_AUTHOR=noreply@panel.occultus.network"
      ## Database settings
      ## change if you want it to be more secure.
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=pterodb"
      - "DB_USERNAME=ptero"
      - "DB_PASSWORD=pterodbpass"
      ## Email settings
      - "MAIL_FROM=noreply@panel.occultus.network"
      - "MAIL_DRIVER=mail"
      - "MAIL_HOST="
      - "MAIL_PORT="
      - "MAIL_USERNAME=''"
      - "MAIL_PASSWORD=''"
      - "MAIL_ENCRYPTION=true"

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  proxy:
    external:
      name: proxy
